// Individual tool entries power the catalog and deep-link search.
export const TOOL_PAGES = [
  { studioId: 'json-studio', id: 'json', name: 'JSON 格式化' },
  { studioId: 'json-studio', id: 'json2ts', name: 'JSON 转代码' },
  { studioId: 'json-studio', id: 'json-schema', name: 'JSON Schema' },
  { studioId: 'json-studio', id: 'xml', name: 'XML 工具' },
  { studioId: 'json-studio', id: 'yaml', name: 'YAML ↔ JSON' },
  { studioId: 'json-studio', id: 'csv', name: 'CSV ↔ JSON' },
  { studioId: 'json-studio', id: 'json-diff', name: 'JSON 结构化对比' },
  { studioId: 'json-studio', id: 'sql-format', name: 'SQL 格式化' },
  { studioId: 'json-studio', id: 'sqlite-sandbox', name: 'SQLite WASM 沙箱' },
  { studioId: 'crypto-studio', id: 'jwt', name: 'JWT 解析' },
  { studioId: 'crypto-studio', id: 'hash', name: 'Hash 生成' },
  { studioId: 'crypto-studio', id: 'hmac', name: 'HMAC 计算' },
  { studioId: 'crypto-studio', id: 'password', name: '密码生成' },
  { studioId: 'crypto-studio', id: 'basic-auth', name: 'Basic Auth 生成器' },
  { studioId: 'crypto-studio', id: 'cert-parser', name: '证书密码解析器' },
  { studioId: 'crypto-studio', id: 'asymmetric-key', name: '非对称密钥转换' },
  { studioId: 'crypto-studio', id: 'pgp-keymaster', name: 'GPG / PGP 密钥中心' },
  { studioId: 'crypto-studio', id: 'sm-crypto', name: '国密算法套件 (SM2/3/4)' },
  { studioId: 'text-studio', id: 'case', name: '大小写转换' },
  { studioId: 'text-studio', id: 'text-manip', name: '文本处理' },
  { studioId: 'text-studio', id: 'slug', name: 'Slug 生成' },
  { studioId: 'text-studio', id: 'stats', name: '文本统计' },
  { studioId: 'text-studio', id: 'regex', name: '正则测试' },
  { studioId: 'text-studio', id: 'diff', name: '文本对比' },
  { studioId: 'encoding-studio', id: 'base64', name: 'Base64 转换' },
  { studioId: 'encoding-studio', id: 'file-base64', name: 'Base64/文件转换器' },
  { studioId: 'encoding-studio', id: 'hex-viewer', name: '十六进制 Hex 查看器' },
  { studioId: 'encoding-studio', id: 'hex-text', name: 'Hex 字节转文本' },
  { studioId: 'encoding-studio', id: 'unicode-inspector', name: 'Unicode 字符检查器' },
  { studioId: 'encoding-studio', id: 'url', name: 'URL 编码' },
  { studioId: 'encoding-studio', id: 'escape', name: 'HTML/Uni 转义' },
  { studioId: 'html-markdown-studio', id: 'markdown', name: 'Markdown 预览' },
  { studioId: 'html-markdown-studio', id: 'html-markdown', name: 'HTML 转 Markdown' },
  { studioId: 'html-markdown-studio', id: 'html-format', name: 'HTML 格式化/压缩器' },
  { studioId: 'network-studio', id: 'http', name: 'HTTP 请求' },
  { studioId: 'network-studio', id: 'websocket-sse', name: 'WebSocket & SSE 沙箱' },
  { studioId: 'network-studio', id: 'ping', name: 'Ping 延迟诊断' },
  { studioId: 'network-studio', id: 'urlparser', name: 'URL 解析器' },
  { studioId: 'network-studio', id: 'useragent', name: 'User Agent' },
  { studioId: 'network-studio', id: 'ip', name: 'IP 信息' },
  { studioId: 'network-studio', id: 'device', name: '设备信息' },
  { studioId: 'network-studio', id: 'video-download', name: '视频下载解析' },
  { studioId: 'repo-dependency-studio', id: 'github-repos', name: 'GitHub 仓库浏览器' },
  { studioId: 'repo-dependency-studio', id: 'github-org-research', name: 'GitHub 组织关联研究' },
  { studioId: 'repo-dependency-studio', id: 'repo-folder-download', name: '仓库文件夹下载' },
  { studioId: 'repo-dependency-studio', id: 'nuget-deps', name: 'NuGet 依赖树' },
  { studioId: 'repo-dependency-studio', id: 'pypi-deps', name: 'PyPI 依赖树' },
  { studioId: 'repo-dependency-studio', id: 'rust-deps', name: 'Rust Crate 依赖树' },
  { studioId: 'repo-dependency-studio', id: 'nuget-signature', name: 'NuGet 签名检查' },
  { studioId: 'css-studio', id: 'pxrem', name: 'PX/REM 转换' },
  { studioId: 'css-studio', id: 'color', name: '颜色转换' },
  { studioId: 'css-studio', id: 'css-generator', name: 'CSS 可视化生成器' },
  { studioId: 'css-studio', id: 'svg-css', name: 'SVG 转 CSS' },
  { studioId: 'css-studio', id: 'svg-optimizer', name: 'SVG 智能压缩' },
  { studioId: 'css-studio', id: 'html-jsx', name: 'HTML 转 JSX' },
  { studioId: 'css-studio', id: 'svg-react', name: 'SVG 转 React' },
  { studioId: 'image-studio', id: 'image', name: '图片压缩/转换' },
  { studioId: 'image-studio', id: 'background-removal', name: '智能本地抠图' },
  { studioId: 'image-studio', id: 'image-base64', name: '图片转 Base64' },
  { studioId: 'image-studio', id: 'image-colors', name: '图片颜色提取' },
  { studioId: 'image-studio', id: 'image-watermark', name: '图片水印' },
  { studioId: 'image-studio', id: 'visual-centroid', name: '视觉质心计算器' },
  { studioId: 'image-studio', id: 'perler-beads', name: '拼豆图纸生成' },
  { studioId: 'image-studio', id: 'headshot', name: '大头照提取' },
  { studioId: 'image-studio', id: 'animation-frame', name: '动画帧提取' },
  { studioId: 'image-studio', id: 'video-download', name: '视频下载解析' },
  { studioId: 'file-studio', id: 'pdf', name: 'PDF 工具箱' },
  { studioId: 'file-studio', id: 'file-info', name: '文件属性信息' },
  { studioId: 'file-studio', id: 'filename', name: '文件名路径提取' },
  { studioId: 'file-studio', id: 'mime', name: 'MIME 类型速查' },
  { studioId: 'cad-3d-studio', id: 'jewelry', name: 'AI 首饰定制' },
  { studioId: 'cad-3d-studio', id: 'stl-repair', name: 'STL 修复/降面' },
  { studioId: 'cad-3d-studio', id: 'stl-voronoi', name: 'STL 镂空/Voronoi' },
  { studioId: 'cad-3d-studio', id: '3d-csg', name: '3D 实体布尔运算' },
  { studioId: 'cad-3d-studio', id: 'smart-geometry', name: '小学几何解题' },
  { studioId: 'system-ai-studio', id: 'uuid', name: 'UUID 生成' },
  { studioId: 'system-ai-studio', id: 'random-str', name: '随机字符串' },
  { studioId: 'system-ai-studio', id: 'random-number', name: '随机数生成器' },
  { studioId: 'system-ai-studio', id: 'lorem', name: '占位与 Mock 数据' },
  { studioId: 'system-ai-studio', id: 'rmb-uppercase', name: '人民币大写' },
  { studioId: 'system-ai-studio', id: 'chmod', name: 'Chmod 计算' },
  { studioId: 'system-ai-studio', id: 'cron', name: 'Cron 表达式' },
  { studioId: 'system-ai-studio', id: 'unix-time-studio', name: '时间与时区工作室' },
  { studioId: 'system-ai-studio', id: 'qrcode', name: '二维码生成' },
  { studioId: 'system-ai-studio', id: 'arithmancy', name: '数字占卜' },
] as const;
